import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Navbar from "./components/Navbar";

const bengali = Noto_Serif_Bengali({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata = {
  title: "IRD Hadith App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bengali.className}>
        <div className="relative">
          <Header></Header>
          <Navbar></Navbar>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
