import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Navbar from "./components/Navbar";

const myFont = localFont({
  src: "../public/fonts/kalpurush.ttf",
  display: "swap",
});

export const metadata = {
  title: "IRD Hadith App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <div className="relative">
          <Header></Header>
          <Navbar></Navbar>
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
